spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 981208
    username: root
    url: jdbc:mysql://localhost:3306/graduation?characterEncoding=utf-8&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
